name: E2E Tests

on:
  push:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000

      - uses: actions/upload-artifact@v1
        if: always() # / if: failure() <- more suitable for production
        with:
          name: cypress-videos
          path: cypress/videos
