name: E2E Tests

on:
  push:

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - name: Linting
        run: npm run lint
      - name: Format
        run: npm run format

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000

      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
